### ISSUE TITLE
Back in stock also fires for variants that have not yet been saved

### ISSUE THREAD

**Issue by boboldehampsink** [mediabeastnz/craft-commerce-back-in-stock#31]
### Describe the bug

Seeing the following error:

```

Exception 'TypeError' with message 'verbb\backinstock\services\Service::findInterestedEmails(): Argument #1 ($variantId) must be of type int, null given, called in /app/user/vendor/verbb/back-in-stock/src/services/Service.php on line 33'
--
  | 2024-11-19 13:29:48 UTC |  
  | 2024-11-19 13:29:48 UTC | in /app/user/vendor/verbb/back-in-stock/src/services/Service.php:42
  | 2024-11-19 13:29:48 UTC |  
  | 2024-11-19 13:29:48 UTC | Stack trace:
  | 2024-11-19 13:29:48 UTC | #0 /app/user/vendor/verbb/back-in-stock/src/services/Service.php(33): verbb\backinstock\services\Service->findInterestedEmails(NULL)
  | 2024-11-19 13:29:48 UTC | #1 /app/user/vendor/verbb/back-in-stock/src/BackInStock.php(126): verbb\backinstock\services\Service->isBackInStock(Object(craft\commerce\elements\Variant))
  | 2024-11-19 13:29:48 UTC | #2 [internal function]: verbb\backinstock\BackInStock->verbb\backinstock\{closure}(Object(craft\events\ModelEvent))
  | 2024-11-19 13:29:48 UTC | #3 /app/user/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ModelEvent))
  | 2024-11-19 13:29:48 UTC | #4 /app/user/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\commerce\\...', 'beforeSave', Object(craft\events\ModelEvent))
  | 2024-11-19 13:29:48 UTC | #5 /app/user/vendor/craftcms/cms/src/base/Element.php(5163): yii\base\Component->trigger('beforeSave', Object(craft\events\ModelEvent))
  | 2024-11-19 13:29:48 UTC | #6 /app/user/vendor/craftcms/commerce/src/elements/Variant.php(1172): craft\base\Element->beforeSave(true)
  | 2024-11-19 13:29:48 UTC | #7 /app/user/vendor/craftcms/cms/src/services/Elements.php(3245): craft\commerce\elements\Variant->beforeSave(true)

...
```

### Steps to reproduce

1. Create a new variant programatically with unlimitedStock

### Craft CMS version

4

### Plugin version

3.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [3.0.2](https://github.com/verbb/back-in-stock/releases/tag/3.0.2)
