### ISSUE TITLE
Error when loading backend log page

### ISSUE THREAD

**Issue by white-lukas** [mediabeastnz/craft-commerce-back-in-stock#34]
### Describe the bug

When opening the logs page in Craft the page keeps loading and the following error occurs

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'variants.productId' in 'on clause' in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute(NULL)
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(411): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /var/www/html/vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /var/www/html/vendor/verbb/back-in-stock/src/controllers/LogsController.php(63): yii\db\Query->count()
#7 [internal function]: verbb\backinstock\controllers\LogsController->actionGetLogs()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-logs', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('craft-commerce-...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('craft-commerce-...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/web/index.php(13): yii\base\Application->run()
#16 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'variants.productId' in 'on clause'
The SQL being executed was: SELECT COUNT(*)
FROM `backinstock_records` `logs`
LEFT JOIN `commerce_variants` `variants` ON `logs`.`variantId` = `variants`.`id`
LEFT JOIN `commerce_products` `products` ON `variants`.`productId` = `products`.`id` in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT COUNT(*)...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(497): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(411): yii\db\Query->queryScalar('COUNT(*)', NULL)
#5 /var/www/html/vendor/yiisoft/yii2/db/Query.php(368): craft\db\Query->queryScalar('COUNT(*)', NULL)
#6 /var/www/html/vendor/verbb/back-in-stock/src/controllers/LogsController.php(63): yii\db\Query->count()
#7 [internal function]: verbb\backinstock\controllers\LogsController->actionGetLogs()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-logs', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('craft-commerce-...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('craft-commerce-...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/web/index.php(13): yii\base\Application->run()
#16 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'variants.productId' in 'on clause'
)
```

### Steps to reproduce

1.  Install plugin
2. Open log page `back-in-stock/logs`

### Craft CMS version

5.5.6

### Plugin version

4.0.3

### Multi-site?

yes

**Comment by engram-design** [comment]
Should be fixed in [4.0.4](https://github.com/verbb/back-in-stock/releases/tag/4.0.4)
